import mongoose from 'mongoose'
import Mod from '../models/Mod'
import { config } from '../config/env'

const mods = [
  {
    title: 'ProMods Map 2.73',
    slug: 'promods-map-273',
    shortDescription: 'The largest map mod for ETS2, adding new countries, cities, and scenic routes.',
    description: 'ProMods is the most comprehensive map mod for Euro Truck Simulator 2, adding thousands of kilometers of new roads across Europe. Explore new countries, rebuilt cities, and detailed landscapes with custom signs, companies, and vegetation.',
    author: 'ProMods Team',
    game: 'ETS2',
    category: 'Maps',
    tags: ['map', 'europe', 'cities', 'roads', 'scenic'],
    version: '2.73',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/1a1a2e/ffffff?text=ProMods',
    screenshots: ['https://placehold.co/800x450/1a1a2e/ffffff?text=ProMods+1', 'https://placehold.co/800x450/1a1a2e/ffffff?text=ProMods+2', 'https://placehold.co/800x450/1a1a2e/ffffff?text=ProMods+3'],
    price: 0,
    isFree: true,
    featured: true,
    status: 'Published',
    downloadCount: 245000,
    rating: 4.9,
    reviewCount: 12800,
    fileSize: '850 MB',
    shareModsUrl: 'https://sharemods.com/promods',
    dependencies: ['ProMods Europe Def/Map Package'],
    changelog: ['Updated for game version 1.53', 'Added new cities in Iceland', 'Fixed road connections in France', 'Improved terrain textures'],
    features: ['Over 20 new cities', 'Custom company skins', 'Realistic road networks', 'Compatible with major map mods', 'High-res terrain textures'],
    requiredDLC: ['Going East DLC', 'Scandinavia DLC'],
    ratingBreakdown: { 5: 10240, 4: 1920, 3: 512, 2: 96, 1: 32 },
    views: 890000,
    purchasesCount: 0,
  },
  {
    title: 'JBX Graphics 2.0',
    slug: 'jbx-graphics-20',
    shortDescription: 'Ultimate graphics overhaul with realistic lighting, weather, and reflections.',
    description: 'JBX Graphics transforms ETS2 with stunning HDR lighting, realistic skyboxes, improved weather effects, and enhanced reflections. Experience the game like never before with cinematic visuals.',
    author: 'JBX Designs',
    game: 'ETS2',
    category: 'Graphics',
    tags: ['graphics', 'lighting', 'hdr', 'weather', 'realistic'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/16213e/ffffff?text=JBX+Graphics',
    screenshots: ['https://placehold.co/800x450/16213e/ffffff?text=JBX+1', 'https://placehold.co/800x450/16213e/ffffff?text=JBX+2', 'https://placehold.co/800x450/16213e/ffffff?text=JBX+3'],
    price: 9.99,
    isFree: false,
    featured: true,
    status: 'Published',
    downloadCount: 189000,
    rating: 4.8,
    reviewCount: 9500,
    fileSize: '450 MB',
    shareModsUrl: 'https://sharemods.com/jbx',
    dependencies: [],
    changelog: ['New HDR lighting engine', 'Improved night skybox', 'Added volumetric fog', 'Optimized performance'],
    features: ['8K HDR skyboxes', 'Volumetric fog system', 'Realistic water reflections', 'Dynamic weather transitions', 'Performance optimized presets'],
    requiredDLC: [],
    ratingBreakdown: { 5: 7600, 4: 1425, 3: 380, 2: 76, 1: 19 },
    views: 650000,
    purchasesCount: 45000,
  },
  {
    title: 'Real Companies & Gas Stations',
    slug: 'real-companies-gas-stations',
    shortDescription: 'Replaces all in-game companies with real-world brands.',
    description: 'This mod replaces every fictional company in ETS2 with real-world brands. See Shell, BP, Exxon, Walmart, Amazon, and many more as you haul cargo across Europe.',
    author: 'Schumi',
    game: 'ETS2',
    category: 'Graphics',
    tags: ['companies', 'brands', 'realism', 'skins'],
    version: '4.8',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/0f3460/ffffff?text=Real+Companies',
    screenshots: ['https://placehold.co/800x450/0f3460/ffffff?text=Real+Companies+1', 'https://placehold.co/800x450/0f3460/ffffff?text=Real+Companies+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 312000,
    rating: 4.7,
    reviewCount: 15200,
    fileSize: '120 MB',
    dependencies: [],
    changelog: ['Added new brands', 'Updated for 1.53', 'Fixed texture errors'],
    features: ['200+ real company skins', 'Real gas station brands', 'Logistics company branding', 'Regular updates'],
    requiredDLC: [],
    ratingBreakdown: { 5: 12160, 4: 2280, 3: 608, 2: 122, 1: 30 },
    views: 1100000,
    purchasesCount: 0,
  },
  {
    title: 'Real Traffic Density & Behavior',
    slug: 'real-traffic-density',
    shortDescription: 'Realistic traffic density and AI behavior for a more immersive experience.',
    description: 'Adjusts traffic density to match real-world levels, improves AI driving behavior, and adds more variety to vehicles on the road.',
    author: 'Cip',
    game: 'ETS2',
    category: 'AI Traffic',
    tags: ['traffic', 'ai', 'density', 'realism'],
    version: '2.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1b1b2f/ffffff?text=Real+Traffic',
    screenshots: ['https://placehold.co/800x450/1b1b2f/ffffff?text=Traffic+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 198000,
    rating: 4.6,
    reviewCount: 8700,
    fileSize: '45 MB',
    dependencies: [],
    changelog: ['Adjusted density values', 'Improved AI lane changes', 'Added emergency vehicles'],
    features: ['Customizable density sliders', 'Realistic AI behavior', 'Emergency vehicle support', 'Traffic variety pack'],
    requiredDLC: [],
    ratingBreakdown: { 5: 6960, 4: 1305, 3: 348, 2: 70, 1: 17 },
    views: 720000,
    purchasesCount: 0,
  },
  {
    title: 'Sound Fixes Pack',
    slug: 'sound-fixes-pack',
    shortDescription: 'Comprehensive sound improvements for engines, environment, and effects.',
    description: 'The Sound Fixes Pack replaces and enhances hundreds of sounds in ETS2 including engine sounds, tire noise, wind, rain, and ambient environmental audio.',
    author: 'Drive Safely',
    game: 'ETS2',
    category: 'Sound',
    tags: ['sound', 'engine', 'audio', 'realism', 'environment'],
    version: '24.10',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/2d2d44/ffffff?text=Sound+Fixes',
    screenshots: ['https://placehold.co/800x450/2d2d44/ffffff?text=Sound+Fixes+1', 'https://placehold.co/800x450/2d2d44/ffffff?text=Sound+Fixes+2'],
    price: 0,
    isFree: true,
    featured: true,
    status: 'Published',
    downloadCount: 456000,
    rating: 4.8,
    reviewCount: 22100,
    fileSize: '280 MB',
    dependencies: [],
    changelog: ['New engine sounds for Scania', 'Improved rain audio', 'Fixed air brake sound', 'Added trailer sounds'],
    features: ['500+ enhanced sounds', 'Binaural audio engine', 'Realistic engine recordings', 'Environmental immersion pack'],
    requiredDLC: [],
    ratingBreakdown: { 5: 17680, 4: 3315, 3: 884, 2: 177, 1: 44 },
    views: 1600000,
    purchasesCount: 0,
  },
  {
    title: 'Brutal Weather',
    slug: 'brutal-weather',
    shortDescription: 'Extreme weather conditions including storms, blizzards, and heavy rain.',
    description: 'Brutal Weather introduces extreme weather conditions to ETS2. Experience massive thunderstorms, heavy snowfall, dense fog, and powerful winds that affect handling.',
    author: 'DarkCap',
    game: 'ETS2',
    category: 'Weather',
    tags: ['weather', 'storm', 'rain', 'snow', 'extreme'],
    version: '4.2',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a1a3e/ffffff?text=Brutal+Weather',
    screenshots: ['https://placehold.co/800x450/1a1a3e/ffffff?text=Weather+1', 'https://placehold.co/800x450/1a1a3e/ffffff?text=Weather+2', 'https://placehold.co/800x450/1a1a3e/ffffff?text=Weather+3'],
    price: 4.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 89000,
    rating: 4.5,
    reviewCount: 4300,
    fileSize: '95 MB',
    dependencies: [],
    changelog: ['Added thunderstorm variant', 'Improved snow accumulation', 'New fog system'],
    features: ['Extreme weather system', 'Dynamic storm generation', 'Snow accumulation physics', 'Wind effects on handling'],
    requiredDLC: [],
    ratingBreakdown: { 5: 3440, 4: 645, 3: 172, 2: 34, 1: 9 },
    views: 310000,
    purchasesCount: 18000,
  },
  {
    title: 'Real Fuel Prices',
    slug: 'real-fuel-prices',
    shortDescription: 'Dynamic fuel pricing based on real-world European fuel costs.',
    description: 'This mod updates fuel prices in ETS2 to reflect real-world European fuel costs. Prices update dynamically and vary by region just like in real life.',
    author: 'Mackintosh',
    game: 'ETS2',
    category: 'Utility',
    tags: ['fuel', 'economy', 'realism', 'prices'],
    version: '3.1',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a4a/ffffff?text=Fuel+Prices',
    screenshots: ['https://placehold.co/800x450/2a2a4a/ffffff?text=Fuel+Prices+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 67000,
    rating: 4.3,
    reviewCount: 3100,
    fileSize: '15 MB',
    dependencies: [],
    changelog: ['Updated price data', 'Added Scandinavian regions'],
    features: ['Real-world fuel prices', 'Regional price variation', 'Dynamic updates', 'Economy integration'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2480, 4: 465, 3: 124, 2: 25, 1: 6 },
    views: 240000,
    purchasesCount: 0,
  },
  {
    title: 'Volvo FH 2022',
    slug: 'volvo-fh-2022',
    shortDescription: 'Detailed Volvo FH 2022 truck with custom interior and tuning options.',
    description: 'The Volvo FH 2022 mod brings the latest Volvo truck to ETS2 with an accurately modeled exterior, detailed interior cabin, custom dashboard, and extensive tuning options including LED lighting and custom rims.',
    author: 'Volvo Team',
    game: 'ETS2',
    category: 'Truck',
    tags: ['volvo', 'fh', '2022', 'truck', 'interior'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/003366/ffffff?text=Volvo+FH+2022',
    screenshots: ['https://placehold.co/800x450/003366/ffffff?text=Volvo+1', 'https://placehold.co/800x450/003366/ffffff?text=Volvo+2', 'https://placehold.co/800x450/003366/ffffff?text=Volvo+3'],
    price: 14.99,
    isFree: false,
    featured: true,
    status: 'Published',
    downloadCount: 156000,
    rating: 4.8,
    reviewCount: 7800,
    fileSize: '320 MB',
    dependencies: [],
    changelog: ['New dashboard layout', 'Added LED headlights', 'Improved engine sound', 'New customization options'],
    features: ['Ultra-detailed exterior model', 'Full interior cabin', 'Custom LED lighting', 'Multiple chassis options', 'Authentic engine sounds'],
    requiredDLC: ['Cabin Accessories DLC'],
    ratingBreakdown: { 5: 6240, 4: 1170, 3: 312, 2: 62, 1: 16 },
    views: 540000,
    purchasesCount: 35000,
  },
  {
    title: 'Scania NG Custom',
    slug: 'scania-ng-custom',
    shortDescription: 'Next-gen Scania truck with custom parts and tuning options.',
    description: 'The Scania NG Custom mod offers a highly detailed next-gen Scania with hundreds of custom parts, bumper options, side skirts, exhausts, and interior accessories.',
    author: 'Eugene',
    game: 'ETS2',
    category: 'Truck',
    tags: ['scania', 'ng', 'custom', 'tuning', 'truck'],
    version: '3.5',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/2d2d2d/ffffff?text=Scania+NG',
    screenshots: ['https://placehold.co/800x450/2d2d2d/ffffff?text=Scania+1', 'https://placehold.co/800x450/2d2d2d/ffffff?text=Scania+2', 'https://placehold.co/800x450/2d2d2d/ffffff?text=Scania+3'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 234000,
    rating: 4.7,
    reviewCount: 11400,
    fileSize: '180 MB',
    dependencies: [],
    changelog: ['Added new bumper options', 'Fixed interior lighting', 'New tuning parts'],
    features: ['200+ custom parts', 'Multiple cabin options', 'Custom sound pack', 'High-res interior textures'],
    requiredDLC: [],
    ratingBreakdown: { 5: 9120, 4: 1710, 3: 456, 2: 91, 1: 23 },
    views: 820000,
    purchasesCount: 0,
  },
  {
    title: 'DAF XD',
    slug: 'daf-xd',
    shortDescription: 'Highly detailed DAF XD distribution truck for ETS2.',
    description: 'The DAF XD mod brings the latest distribution truck from DAF to ETS2. Features a detailed cabin, accurate engine sounds, and multiple chassis configurations for distribution and regional haul.',
    author: 'DAF Modding',
    game: 'ETS2',
    category: 'Truck',
    tags: ['daf', 'xd', 'truck', 'distribution'],
    version: '1.8',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a3a5c/ffffff?text=DAF+XD',
    screenshots: ['https://placehold.co/800x450/1a3a5c/ffffff?text=DAF+1', 'https://placehold.co/800x450/1a3a5c/ffffff?text=DAF+2'],
    price: 7.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 45000,
    rating: 4.4,
    reviewCount: 2100,
    fileSize: '250 MB',
    dependencies: [],
    changelog: ['Added new engine option', 'Fixed mirror positioning'],
    features: ['Detailed DAF XD model', 'Multiple chassis options', 'Accurate PACCAR engine sounds', 'Custom dashboard'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1680, 4: 315, 3: 84, 2: 17, 1: 4 },
    views: 160000,
    purchasesCount: 12000,
  },
  {
    title: 'Mercedes Actros MP5',
    slug: 'mercedes-actros-mp5',
    shortDescription: 'Mercedes-Benz Actros MP5 with full interior and tuning.',
    description: 'Detailed Mercedes Actros MP5 featuring the new ProCabin, multimedia cockpit, and MirrorCam system. Includes multiple cabin variants and extensive tuning parts.',
    author: 'Actros Modding',
    game: 'ETS2',
    category: 'Truck',
    tags: ['mercedes', 'actros', 'mp5', 'truck'],
    version: '2.2',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1b2a3a/ffffff?text=Actros+MP5',
    screenshots: ['https://placehold.co/800x450/1b2a3a/ffffff?text=Actros+1', 'https://placehold.co/800x450/1b2a3a/ffffff?text=Actros+2'],
    price: 12.99,
    isFree: false,
    featured: true,
    status: 'Published',
    downloadCount: 98000,
    rating: 4.6,
    reviewCount: 4900,
    fileSize: '290 MB',
    dependencies: [],
    changelog: ['MirrorCam support', 'New interior textures', 'Added tuning parts'],
    features: ['ProCabin interior', 'MirrorCam system', 'Multimedia cockpit', 'Extensive tuning options'],
    requiredDLC: ['Cabin Accessories DLC'],
    ratingBreakdown: { 5: 3920, 4: 735, 3: 196, 2: 39, 1: 10 },
    views: 340000,
    purchasesCount: 22000,
  },
  {
    title: 'RJL Scania R & S',
    slug: 'rjl-scania-r-s',
    shortDescription: 'Comprehensive Scania R & S truck pack with tuning parts.',
    description: 'RJL Scania R & S is one of the most popular truck mods for ETS2. Includes Scania R and S series with dozens of cabin options, chassis configurations, and tuning parts.',
    author: 'RJL',
    game: 'ETS2',
    category: 'Truck',
    tags: ['scania', 'rjl', 'truck', 'tuning'],
    version: '2.6',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/2a3a4a/ffffff?text=RJL+Scania',
    screenshots: ['https://placehold.co/800x450/2a3a4a/ffffff?text=RJL+1', 'https://placehold.co/800x450/2a3a4a/ffffff?text=RJL+2', 'https://placehold.co/800x450/2a3a4a/ffffff?text=RJL+3'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 312000,
    rating: 4.8,
    reviewCount: 16800,
    fileSize: '210 MB',
    dependencies: [],
    changelog: ['Updated for 1.53', 'New tuning parts', 'Bug fixes', 'Improved reflections'],
    features: ['Complete R and S series', '50+ chassis options', 'High-res textures', 'Custom sound package'],
    requiredDLC: [],
    ratingBreakdown: { 5: 13440, 4: 2520, 3: 672, 2: 134, 1: 34 },
    views: 1100000,
    purchasesCount: 0,
  },
  {
    title: 'SiSL Mega Pack',
    slug: 'sisl-mega-pack',
    shortDescription: 'Huge collection of interior accessories and cabin items.',
    description: 'SiSL Mega Pack adds hundreds of interior accessories to ETS2 including steering wheels, shifters, GPS units, toys, flags, dash decorations, and much more.',
    author: 'SiSL',
    game: 'ETS2',
    category: 'Interior',
    tags: ['interior', 'accessories', 'cabin', 'customization'],
    version: '5.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a3a/ffffff?text=SiSL+Mega+Pack',
    screenshots: ['https://placehold.co/800x450/3a2a3a/ffffff?text=SiSL+1', 'https://placehold.co/800x450/3a2a3a/ffffff?text=SiSL+2', 'https://placehold.co/800x450/3a2a3a/ffffff?text=SiSL+3'],
    price: 0,
    isFree: true,
    featured: true,
    status: 'Published',
    downloadCount: 534000,
    rating: 4.9,
    reviewCount: 25600,
    fileSize: '160 MB',
    dependencies: [],
    changelog: ['50 new accessories', 'New GPS models', 'Bug fixes', 'Improved compatibility'],
    features: ['500+ interior accessories', 'Custom steering wheels', 'GPS navigation units', 'Seat covers and toys', 'Regular content updates'],
    requiredDLC: ['Cabin Accessories DLC'],
    ratingBreakdown: { 5: 20480, 4: 3840, 3: 1024, 2: 205, 1: 51 },
    views: 1900000,
    purchasesCount: 0,
  },
  {
    title: 'Krone MegaLiner',
    slug: 'krone-megaliner',
    shortDescription: 'Detailed Krone MegaLiner trailer pack with skins and upgrades.',
    description: 'The Krone MegaLiner pack adds the famous Krone trailers to ETS2 with detailed models, multiple cargo configurations, and a variety of company skins.',
    author: 'Krone Team',
    game: 'ETS2',
    category: 'Trailer',
    tags: ['krone', 'trailer', 'megaliner', 'cargo'],
    version: '3.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a4a2a/ffffff?text=Krone+MegaLiner',
    screenshots: ['https://placehold.co/800x450/2a4a2a/ffffff?text=Krone+1', 'https://placehold.co/800x450/2a4a2a/ffffff?text=Krone+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 178000,
    rating: 4.6,
    reviewCount: 8900,
    fileSize: '95 MB',
    dependencies: ['Krone Trailer Pack DLC'],
    changelog: ['New company skins', 'Updated cargo models', 'Fixed shadow issues'],
    features: ['Detailed Krone trailers', 'Multiple cargo configs', 'Company skin pack', 'Tuning accessories'],
    requiredDLC: ['Krone Trailer Pack DLC'],
    ratingBreakdown: { 5: 7120, 4: 1335, 3: 356, 2: 71, 1: 18 },
    views: 620000,
    purchasesCount: 0,
  },
  {
    title: 'Physics Mod Ultimate',
    slug: 'physics-mod-ultimate',
    shortDescription: 'Complete physics overhaul with realistic suspension and handling.',
    description: 'Physics Mod Ultimate completely overhauls the vehicle physics in ETS2 including suspension, braking, tire grip, weight transfer, and damage model.',
    author: 'Kirby',
    game: 'ETS2',
    category: 'Physics',
    tags: ['physics', 'suspension', 'handling', 'realism'],
    version: '5.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a2a2a/ffffff?text=Physics+Ultimate',
    screenshots: ['https://placehold.co/800x450/1a2a2a/ffffff?text=Physics+1', 'https://placehold.co/800x450/1a2a2a/ffffff?text=Physics+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 145000,
    rating: 4.5,
    reviewCount: 7200,
    fileSize: '35 MB',
    dependencies: [],
    changelog: ['Improved tire physics', 'Adjusted suspension damping', 'New weight distribution model'],
    features: ['Realistic suspension simulation', 'Advanced tire grip model', 'Weight transfer physics', 'Enhanced damage model'],
    requiredDLC: [],
    ratingBreakdown: { 5: 5760, 4: 1080, 3: 288, 2: 58, 1: 14 },
    views: 500000,
    purchasesCount: 0,
  },
  {
    title: 'Realistic Rain & Thunder',
    slug: 'realistic-rain-thunder',
    shortDescription: 'Enhanced rain effects and thunder sounds for immersive driving.',
    description: 'This mod enhances rain effects with better water droplets, road reflections, puddle formation, and realistic thunder sound effects.',
    author: 'DarkCap',
    game: 'ETS2',
    category: 'Weather',
    tags: ['rain', 'weather', 'thunder', 'immersion'],
    version: '3.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a4e/ffffff?text=Rain+Thunder',
    screenshots: ['https://placehold.co/800x450/2a2a4e/ffffff?text=Rain+1', 'https://placehold.co/800x450/2a2a4e/ffffff?text=Rain+2'],
    price: 2.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 34000,
    rating: 4.2,
    reviewCount: 1600,
    fileSize: '55 MB',
    dependencies: [],
    changelog: ['New thunder sound effects', 'Improved rain particle system'],
    features: ['Enhanced rain effects', 'Realistic thunder audio', 'Road puddle formation', 'Windshield rain effects'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1280, 4: 240, 3: 64, 2: 13, 1: 3 },
    views: 120000,
    purchasesCount: 8000,
  },
  {
    title: 'MAN TGX 2023',
    slug: 'man-tgx-2023',
    shortDescription: 'Detailed MAN TGX 2023 with Individual Lion design.',
    description: 'The MAN TGX 2023 mod features the latest MAN truck with Individual Lion specification, including custom grille, LED lighting, and a luxurious interior.',
    author: 'MAN Mods',
    game: 'ETS2',
    category: 'Truck',
    tags: ['man', 'tgx', '2023', 'truck'],
    version: '1.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a2a3a/ffffff?text=MAN+TGX+2023',
    screenshots: ['https://placehold.co/800x450/1a2a3a/ffffff?text=MAN+1', 'https://placehold.co/800x450/1a2a3a/ffffff?text=MAN+2'],
    price: 6.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 52000,
    rating: 4.3,
    reviewCount: 2500,
    fileSize: '270 MB',
    dependencies: [],
    changelog: ['Added Individual Lion trim', 'New dashboard layout'],
    features: ['MAN TGX 2023 model', 'Individual Lion trim', 'LED lighting package', 'Custom interior options'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2000, 4: 375, 3: 100, 2: 20, 1: 5 },
    views: 180000,
    purchasesCount: 14000,
  },
  {
    title: 'Project Japan Map',
    slug: 'project-japan-map',
    shortDescription: 'Drive through detailed recreation of Japan in ETS2.',
    description: 'Project Japan brings Japanese highways, cities, and landscapes to ETS2. Drive through Tokyo, Osaka, and rural Japan with accurate road signage and architecture.',
    author: 'Project Japan Team',
    game: 'ETS2',
    category: 'Maps',
    tags: ['map', 'japan', 'asia', 'cities'],
    version: '1.2',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a1a/ffffff?text=Project+Japan',
    screenshots: ['https://placehold.co/800x450/3a2a1a/ffffff?text=Japan+1', 'https://placehold.co/800x450/3a2a1a/ffffff?text=Japan+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 67000,
    rating: 4.4,
    reviewCount: 3200,
    fileSize: '420 MB',
    dependencies: ['ProMods Map 2.73'],
    changelog: ['Added Osaka', 'Fixed road connections', 'New landmarks'],
    features: ['Japan map expansion', 'Accurate road signage', 'Authentic architecture', 'Scenic routes'],
    requiredDLC: ['Going East DLC'],
    ratingBreakdown: { 5: 2560, 4: 480, 3: 128, 2: 26, 1: 6 },
    views: 240000,
    purchasesCount: 0,
  },
  {
    title: 'Kenworth W900',
    slug: 'kenworth-w900',
    shortDescription: 'Iconic American truck for ETS2 with full customization.',
    description: 'The Kenworth W900 brings this classic American truck to ETS2 with authentic detailing, customized engine sounds, and extensive tuning options.',
    author: 'W900 Modders',
    game: 'ETS2',
    category: 'Truck',
    tags: ['kenworth', 'w900', 'american', 'truck'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a2a/ffffff?text=Kenworth+W900',
    screenshots: ['https://placehold.co/800x450/3a2a2a/ffffff?text=Kenworth+1', 'https://placehold.co/800x450/3a2a2a/ffffff?text=Kenworth+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 89000,
    rating: 4.5,
    reviewCount: 4100,
    fileSize: '195 MB',
    dependencies: [],
    changelog: ['New engine sounds', 'Added chrome accessories', 'Updated interior'],
    features: ['Classic Kenworth W900', 'Cummins engine sounds', 'Chrome accessory pack', 'Detailed interior cabin'],
    requiredDLC: [],
    ratingBreakdown: { 5: 3280, 4: 615, 3: 164, 2: 33, 1: 8 },
    views: 310000,
    purchasesCount: 0,
  },
  {
    title: 'RusMap',
    slug: 'rusmap',
    shortDescription: 'Extensive map of Russia and surrounding regions for ETS2.',
    description: 'RusMap adds thousands of kilometers of roads across Russia, Belarus, and Ukraine. Features detailed cities, industrial zones, and scenic countryside.',
    author: 'RusMap Team',
    game: 'ETS2',
    category: 'Maps',
    tags: ['map', 'russia', 'eastern-europe', 'roads'],
    version: '2.52',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a3a/ffffff?text=RusMap',
    screenshots: ['https://placehold.co/800x450/2a3a3a/ffffff?text=RusMap+1', 'https://placehold.co/800x450/2a3a3a/ffffff?text=RusMap+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 198000,
    rating: 4.6,
    reviewCount: 9600,
    fileSize: '580 MB',
    dependencies: ['ProMods Map 2.73'],
    changelog: ['Updated road network', 'New cities added', 'Improved terrain'],
    features: ['Eastern Europe expansion', 'Detailed Russian cities', 'Industrial zones', 'Compatible with ProMods'],
    requiredDLC: ['Going East DLC'],
    ratingBreakdown: { 5: 7680, 4: 1440, 3: 384, 2: 77, 1: 19 },
    views: 690000,
    purchasesCount: 0,
  },
  {
    title: 'Paint Job Pack - Carbon Fiber',
    slug: 'paint-job-carbon-fiber',
    shortDescription: 'Premium carbon fiber paint jobs for all trucks.',
    description: 'A collection of carbon fiber paint jobs for every truck in ETS2. Includes multiple carbon fiber patterns, colors, and finishes.',
    author: 'Paint Masters',
    game: 'ETS2',
    category: 'Paint Jobs',
    tags: ['paint', 'carbon', 'skin', 'customization'],
    version: '1.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a1a1a/ffffff?text=Carbon+Paint',
    screenshots: ['https://placehold.co/800x450/1a1a1a/ffffff?text=Carbon+1'],
    price: 3.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 28000,
    rating: 4.1,
    reviewCount: 1300,
    fileSize: '85 MB',
    dependencies: [],
    changelog: ['Initial release'],
    features: ['Carbon fiber patterns', 'Multiple color variants', 'Gloss and matte finishes', 'Works on all trucks'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1040, 4: 195, 3: 52, 2: 11, 1: 2 },
    views: 100000,
    purchasesCount: 7000,
  },
  {
    title: 'Bus Mod - MAN Lion\'s Coach',
    slug: 'bus-man-lions-coach',
    shortDescription: 'Drive the MAN Lion\'s Coach bus in ETS2.',
    description: 'This mod adds the MAN Lion\'s Coach bus to ETS2. Features a detailed interior, passenger view, and bus stop functionality.',
    author: 'Bus Modders',
    game: 'ETS2',
    category: 'Bus',
    tags: ['bus', 'man', 'passenger', 'coach'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a4e/ffffff?text=MAN+Bus',
    screenshots: ['https://placehold.co/800x450/2a3a4e/ffffff?text=Bus+1', 'https://placehold.co/800x450/2a3a4e/ffffff?text=Bus+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 43000,
    rating: 4.3,
    reviewCount: 2000,
    fileSize: '145 MB',
    dependencies: [],
    changelog: ['New interior design', 'Added passenger animations'],
    features: ['MAN Lion\'s Coach model', 'Detailed passenger cabin', 'Bus stop functionality', 'Passenger view mode'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1600, 4: 300, 3: 80, 2: 16, 1: 4 },
    views: 150000,
    purchasesCount: 0,
  },
  {
    title: 'ETS2 Accessories Pack',
    slug: 'ets2-accessories-pack',
    shortDescription: 'Collection of exterior accessories including lights and bars.',
    description: 'Adds hundreds of exterior accessories to ETS2 including light bars, beacons, roof bars, sun visors, mud flaps, and chrome accessories for all trucks.',
    author: 'Accessory Team',
    game: 'ETS2',
    category: 'Accessories',
    tags: ['accessories', 'lights', 'exterior', 'tuning'],
    version: '3.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a2a/ffffff?text=Accessories',
    screenshots: ['https://placehold.co/800x450/2a3a2a/ffffff?text=Acc+1', 'https://placehold.co/800x450/2a3a2a/ffffff?text=Acc+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 120000,
    rating: 4.5,
    reviewCount: 5800,
    fileSize: '110 MB',
    dependencies: [],
    changelog: ['Added LED light bars', 'New bumper accessories'],
    features: ['300+ exterior accessories', 'LED light bars', 'Chrome accessories', 'Sun visors and roof bars'],
    requiredDLC: [],
    ratingBreakdown: { 5: 4640, 4: 870, 3: 232, 2: 46, 1: 12 },
    views: 420000,
    purchasesCount: 0,
  },
  {
    title: 'Winter Mod',
    slug: 'winter-mod',
    shortDescription: 'Complete winter weather and landscape transformation.',
    description: 'Transform ETS2 into a winter wonderland with snow-covered roads, frozen lakes, snow plows, and winter weather conditions.',
    author: 'Winter Team',
    game: 'ETS2',
    category: 'Weather',
    tags: ['winter', 'snow', 'weather', 'seasonal'],
    version: '4.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/4a4a6a/ffffff?text=Winter+Mod',
    screenshots: ['https://placehold.co/800x450/4a4a6a/ffffff?text=Winter+1', 'https://placehold.co/800x450/4a4a6a/ffffff?text=Winter+2', 'https://placehold.co/800x450/4a4a6a/ffffff?text=Winter+3'],
    price: 0,
    isFree: true,
    featured: true,
    status: 'Published',
    downloadCount: 215000,
    rating: 4.7,
    reviewCount: 10300,
    fileSize: '320 MB',
    dependencies: [],
    changelog: ['Improved snow textures', 'Added ice physics', 'New winter vegetation'],
    features: ['Full winter transformation', 'Snow accumulation system', 'Ice physics simulation', 'Winter vegetation pack'],
    requiredDLC: [],
    ratingBreakdown: { 5: 8240, 4: 1545, 3: 412, 2: 82, 1: 21 },
    views: 750000,
    purchasesCount: 0,
  },
  {
    title: 'Peterbilt 389',
    slug: 'peterbilt-389',
    shortDescription: 'Classic Peterbilt 389 American truck for ETS2.',
    description: 'The Peterbilt 389 brings the iconic American long-nose truck to ETS2. Features authentic Cummins engine sounds, detailed interior, and custom tuning.',
    author: 'American Truck Mods',
    game: 'ETS2',
    category: 'Truck',
    tags: ['peterbilt', '389', 'american', 'truck', 'classic'],
    version: '1.8',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a1a/ffffff?text=Peterbilt+389',
    screenshots: ['https://placehold.co/800x450/3a2a1a/ffffff?text=Peterbilt+1', 'https://placehold.co/800x450/3a2a1a/ffffff?text=Peterbilt+2'],
    price: 8.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 61000,
    rating: 4.4,
    reviewCount: 2900,
    fileSize: '230 MB',
    dependencies: [],
    changelog: ['New engine options', 'Fixed interior bugs'],
    features: ['Classic Peterbilt 389', 'Cummins engine sounds', 'Chrome accessory pack', 'Detailed interior'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2320, 4: 435, 3: 116, 2: 23, 1: 6 },
    views: 210000,
    purchasesCount: 16000,
  },
  {
    title: 'Real Gas Stations USA',
    slug: 'real-gas-stations-usa',
    shortDescription: 'Real American fuel brands for ATS.',
    description: 'Replaces all fuel stations in American Truck Simulator with real American brands including Shell, Exxon, Mobil, Chevron, and Speedway.',
    author: 'Schumi',
    game: 'ATS',
    category: 'Graphics',
    tags: ['gas', 'stations', 'usa', 'brands', 'ats'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a2a4a/ffffff?text=Gas+USA',
    screenshots: ['https://placehold.co/800x450/1a2a4a/ffffff?text=Gas+USA+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 45000,
    rating: 4.3,
    reviewCount: 2100,
    fileSize: '80 MB',
    dependencies: [],
    changelog: ['Added new brands', 'Updated for 1.53'],
    features: ['Real US fuel brands', 'Accurate station models', 'Regional brand distribution'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1680, 4: 315, 3: 84, 2: 17, 1: 4 },
    views: 160000,
    purchasesCount: 0,
  },
  {
    title: 'ATS Real Companies',
    slug: 'ats-real-companies',
    shortDescription: 'Real-world companies and brands for ATS.',
    description: 'Replaces all fictional companies in American Truck Simulator with real American brands and retailers.',
    author: 'Schumi',
    game: 'ATS',
    category: 'Graphics',
    tags: ['companies', 'ats', 'brands', 'realism'],
    version: '3.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a4a/ffffff?text=ATS+Companies',
    screenshots: ['https://placehold.co/800x450/2a3a4a/ffffff?text=ATS+Companies+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 38000,
    rating: 4.2,
    reviewCount: 1800,
    fileSize: '95 MB',
    dependencies: [],
    changelog: ['Updated brand logos', 'Added new companies'],
    features: ['Real US company brands', 'Updated logistics skins', 'Regional cargo branding'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1440, 4: 270, 3: 72, 2: 14, 1: 4 },
    views: 140000,
    purchasesCount: 0,
  },
  {
    title: 'Freightliner Cascadia',
    slug: 'freightliner-cascadia',
    shortDescription: 'Detailed Freightliner Cascadia for ATS.',
    description: 'The Freightliner Cascadia mod brings this popular American truck to ATS with accurate modeling, Detroit Diesel engine sounds, and multiple cab configurations.',
    author: 'Cascadia Mods',
    game: 'ATS',
    category: 'Truck',
    tags: ['freightliner', 'cascadia', 'ats', 'truck'],
    version: '2.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a3a3a/ffffff?text=Cascadia',
    screenshots: ['https://placehold.co/800x450/1a3a3a/ffffff?text=Cascadia+1', 'https://placehold.co/800x450/1a3a3a/ffffff?text=Cascadia+2'],
    price: 11.99,
    isFree: false,
    featured: true,
    status: 'Published',
    downloadCount: 72000,
    rating: 4.5,
    reviewCount: 3500,
    fileSize: '280 MB',
    dependencies: [],
    changelog: ['Added new interior options', 'Improved engine sounds'],
    features: ['Detailed Freightliner Cascadia', 'Detroit Diesel sounds', 'Multiple cab configs', 'Tuning parts'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2800, 4: 525, 3: 140, 2: 28, 1: 7 },
    views: 250000,
    purchasesCount: 18000,
  },
  {
    title: 'International LT',
    slug: 'international-lt',
    shortDescription: 'International LT series truck for ATS with tuning.',
    description: 'Detailed International LT series truck with multiple cabin options, engine choices, and tuning accessories.',
    author: 'International Mods',
    game: 'ATS',
    category: 'Truck',
    tags: ['international', 'lt', 'ats', 'truck'],
    version: '1.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a3a/ffffff?text=Intl+LT',
    screenshots: ['https://placehold.co/800x450/2a2a3a/ffffff?text=Intl+LT+1'],
    price: 5.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 28000,
    rating: 4.1,
    reviewCount: 1300,
    fileSize: '210 MB',
    dependencies: [],
    changelog: ['Initial ATS release'],
    features: ['International LT series', 'Multiple engine options', 'Cabin configurations', 'Tuning accessories'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1040, 4: 195, 3: 52, 2: 11, 1: 2 },
    views: 100000,
    purchasesCount: 7000,
  },
  {
    title: 'Grand Canyon Map',
    slug: 'grand-canyon-map',
    shortDescription: 'Explore Grand Canyon and surrounding areas in ATS.',
    description: 'This map mod adds the Grand Canyon region to American Truck Simulator with scenic routes, vista points, and new delivery locations.',
    author: 'Map Explorers',
    game: 'ATS',
    category: 'Maps',
    tags: ['map', 'grand-canyon', 'scenery', 'usa'],
    version: '1.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a1a/ffffff?text=Grand+Canyon',
    screenshots: ['https://placehold.co/800x450/3a2a1a/ffffff?text=Canyon+1', 'https://placehold.co/800x450/3a2a1a/ffffff?text=Canyon+2', 'https://placehold.co/800x450/3a2a1a/ffffff?text=Canyon+3'],
    price: 0,
    isFree: true,
    featured: true,
    status: 'Published',
    downloadCount: 54000,
    rating: 4.6,
    reviewCount: 2600,
    fileSize: '380 MB',
    dependencies: [],
    changelog: ['Initial release'],
    features: ['Grand Canyon region', 'Scenic viewpoints', 'New delivery locations', 'Custom road networks'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2080, 4: 390, 3: 104, 2: 21, 1: 5 },
    views: 190000,
    purchasesCount: 0,
  },
  {
    title: 'AI Traffic Pack USA',
    slug: 'ai-traffic-pack-usa',
    shortDescription: 'Realistic American traffic vehicles for ATS.',
    description: 'Adds a variety of real American vehicles to ATS traffic including police cars, pickup trucks, SUVs, and commercial vehicles.',
    author: 'Traffic Team',
    game: 'ATS',
    category: 'AI Traffic',
    tags: ['traffic', 'ai', 'usa', 'vehicles', 'ats'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a4a/ffffff?text=Traffic+USA',
    screenshots: ['https://placehold.co/800x450/2a2a4a/ffffff?text=Traffic+USA+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 63000,
    rating: 4.4,
    reviewCount: 3000,
    fileSize: '120 MB',
    dependencies: [],
    changelog: ['Added police vehicles', 'New pickup truck models'],
    features: ['American traffic vehicles', 'Police car models', 'Pickup truck variety', 'Commercial vehicle pack'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2400, 4: 450, 3: 120, 2: 24, 1: 6 },
    views: 220000,
    purchasesCount: 0,
  },
  {
    title: 'Environment Audio Plus',
    slug: 'environment-audio-plus',
    shortDescription: 'Enhanced ambient sounds for a more immersive world.',
    description: 'This mod adds hundreds of new ambient sounds to ETS2 and ATS including birds, insects, wind, water, city sounds, and industrial noises.',
    author: 'Audio Design',
    game: 'ETS2',
    category: 'Sound',
    tags: ['audio', 'environment', 'ambient', 'immersion'],
    version: '2.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a2a/ffffff?text=Audio+Plus',
    screenshots: ['https://placehold.co/800x450/2a3a2a/ffffff?text=Audio+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 76000,
    rating: 4.3,
    reviewCount: 3600,
    fileSize: '210 MB',
    dependencies: [],
    changelog: ['New city ambient sounds', 'Added industrial audio'],
    features: ['Nature ambient sounds', 'City environment audio', 'Industrial zone sounds', 'Weather-based audio'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2880, 4: 540, 3: 144, 2: 29, 1: 7 },
    views: 270000,
    purchasesCount: 0,
  },
  {
    title: 'Real Economy Mod',
    slug: 'real-economy-mod',
    shortDescription: 'Realistic economy and cargo pricing for ETS2/ATS.',
    description: 'Overhauls the in-game economy with realistic cargo prices, fuel costs, tolls, and income balancing. Makes the game more challenging and rewarding.',
    author: 'Economy Modder',
    game: 'ETS2',
    category: 'Utility',
    tags: ['economy', 'cargo', 'prices', 'realism', 'challenge'],
    version: '4.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a4a2a/ffffff?text=Real+Economy',
    screenshots: ['https://placehold.co/800x450/2a4a2a/ffffff?text=Economy+1'],
    price: 2.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 39000,
    rating: 4.0,
    reviewCount: 1800,
    fileSize: '25 MB',
    dependencies: [],
    changelog: ['Adjusted cargo rates', 'New fuel price calculation'],
    features: ['Realistic economy overhaul', 'Dynamic cargo pricing', 'Balanced income system', 'Fuel cost calculation'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1440, 4: 270, 3: 72, 2: 14, 1: 4 },
    views: 140000,
    purchasesCount: 10000,
  },
  {
    title: 'Project Balkans',
    slug: 'project-balkans',
    shortDescription: 'Detailed map of the Balkan region for ETS2.',
    description: 'Project Balkans adds the countries of former Yugoslavia to ETS2 including detailed cities, scenic coastal roads, and mountainous terrain.',
    author: 'Balkans Team',
    game: 'ETS2',
    category: 'Maps',
    tags: ['map', 'balkans', 'europe', 'cities', 'scenic'],
    version: '5.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a2a/ffffff?text=Project+Balkans',
    screenshots: ['https://placehold.co/800x450/3a2a2a/ffffff?text=Balkans+1', 'https://placehold.co/800x450/3a2a2a/ffffff?text=Balkans+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 134000,
    rating: 4.5,
    reviewCount: 6400,
    fileSize: '490 MB',
    dependencies: ['ProMods Map 2.73'],
    changelog: ['Added new cities', 'Updated road network', 'Fixed border crossings'],
    features: ['Balkan region expansion', 'Coastal road networks', 'Mountain passes', 'Custom landmarks'],
    requiredDLC: ['Going East DLC', 'Italia DLC'],
    ratingBreakdown: { 5: 5120, 4: 960, 3: 256, 2: 51, 1: 13 },
    views: 470000,
    purchasesCount: 0,
  },
  {
    title: 'Dashboard Colors',
    slug: 'dashboard-colors',
    shortDescription: 'Customize your truck dashboard with new color schemes.',
    description: 'This mod allows you to customize the dashboard colors of all trucks in ETS2. Choose from dozens of color schemes for gauges, displays, and ambient lighting.',
    author: 'Interior Design',
    game: 'ETS2',
    category: 'Interior',
    tags: ['dashboard', 'colors', 'interior', 'customization'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a3a/ffffff?text=Dashboard+Colors',
    screenshots: ['https://placehold.co/800x450/2a2a3a/ffffff?text=Dashboard+1'],
    price: 1.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 22000,
    rating: 4.0,
    reviewCount: 1000,
    fileSize: '45 MB',
    dependencies: [],
    changelog: ['Added 15 new color schemes'],
    features: ['Dashboard color customization', 'Gauge color options', 'Display theme system', 'Ambient lighting colors'],
    requiredDLC: [],
    ratingBreakdown: { 5: 800, 4: 150, 3: 40, 2: 8, 1: 2 },
    views: 80000,
    purchasesCount: 5500,
  },
  {
    title: 'Promods Middle East Addon',
    slug: 'promods-middle-east',
    shortDescription: 'Middle East expansion for ProMods map.',
    description: 'Adds Middle Eastern countries including Turkey, Israel, Jordan, and Lebanon to the ProMods map with authentic scenery and architecture.',
    author: 'ProMods Team',
    game: 'ETS2',
    category: 'Maps',
    tags: ['map', 'middle-east', 'promods', 'addon'],
    version: '2.8',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/3a2a1a/ffffff?text=Middle+East',
    screenshots: ['https://placehold.co/800x450/3a2a1a/ffffff?text=ME+1', 'https://placehold.co/800x450/3a2a1a/ffffff?text=ME+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 87000,
    rating: 4.4,
    reviewCount: 4100,
    fileSize: '350 MB',
    dependencies: ['ProMods Map 2.73'],
    changelog: ['Added new cities in Turkey'],
    features: ['Middle East expansion', 'New cities and roads', 'Authentic architecture', 'Desert landscapes'],
    requiredDLC: ['Going East DLC'],
    ratingBreakdown: { 5: 3280, 4: 615, 3: 164, 2: 33, 1: 8 },
    views: 300000,
    purchasesCount: 0,
  },
  {
    title: 'Scania V8 Sound Pack',
    slug: 'scania-v8-sound-pack',
    shortDescription: 'Authentic Scania V8 engine sound pack.',
    description: 'High-quality recordings of real Scania V8 engines. Features multiple variants including the 730hp, 770hp, and custom tuned V8s.',
    author: 'Engine Audio',
    game: 'ETS2',
    category: 'Sound',
    tags: ['sound', 'scania', 'v8', 'engine', 'audio'],
    version: '3.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a2a/ffffff?text=Scania+V8',
    screenshots: ['https://placehold.co/800x450/2a2a2a/ffffff?text=V8+1'],
    price: 4.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 56000,
    rating: 4.6,
    reviewCount: 2700,
    fileSize: '180 MB',
    dependencies: [],
    changelog: ['New 770hp sound profile', 'Improved turbo whistle'],
    features: ['Real Scania V8 recordings', 'Multiple engine variants', 'Turbo and exhaust sounds', 'Interior and exterior mix'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2160, 4: 405, 3: 108, 2: 22, 1: 5 },
    views: 200000,
    purchasesCount: 14000,
  },
  {
    title: 'Realistic Tire Physics',
    slug: 'realistic-tire-physics',
    shortDescription: 'Advanced tire physics for different road conditions.',
    description: 'Realistic tire physics that simulates different tire compounds and their behavior on wet, dry, and snowy roads.',
    author: 'Physics Team',
    game: 'ETS2',
    category: 'Physics',
    tags: ['physics', 'tire', 'grip', 'realism', 'handling'],
    version: '1.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a2a3a/ffffff?text=Tire+Physics',
    screenshots: ['https://placehold.co/800x450/1a2a3a/ffffff?text=Tire+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 81000,
    rating: 4.3,
    reviewCount: 3900,
    fileSize: '20 MB',
    dependencies: ['Physics Mod Ultimate'],
    changelog: ['Added wet grip simulation'],
    features: ['Advanced tire physics', 'Road condition simulation', 'Tire compound modeling', 'Temperature effects'],
    requiredDLC: [],
    ratingBreakdown: { 5: 3120, 4: 585, 3: 156, 2: 31, 1: 8 },
    views: 280000,
    purchasesCount: 0,
  },
  {
    title: 'Mack Anthem',
    slug: 'mack-anthem',
    shortDescription: 'Mack Anthem truck for ATS with detailed interior.',
    description: 'The Mack Anthem brings this modern American truck to ATS with Mack engine sounds, multiple cab configurations, and custom tuning parts.',
    author: 'Mack Mods',
    game: 'ATS',
    category: 'Truck',
    tags: ['mack', 'anthem', 'ats', 'truck'],
    version: '1.2',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a4a/ffffff?text=Mack+Anthem',
    screenshots: ['https://placehold.co/800x450/2a3a4a/ffffff?text=Mack+1'],
    price: 9.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 34000,
    rating: 4.2,
    reviewCount: 1600,
    fileSize: '240 MB',
    dependencies: [],
    changelog: ['Improved interior textures'],
    features: ['Mack Anthem model', 'Mack engine sounds', 'Cab configurations', 'Tuning parts'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1280, 4: 240, 3: 64, 2: 13, 1: 3 },
    views: 120000,
    purchasesCount: 9000,
  },
  {
    title: 'Realistic Truck Physics',
    slug: 'realistic-truck-physics',
    shortDescription: 'Realistic weight and inertia for all trucks.',
    description: 'Completely reworks the weight, inertia, and center of mass for all trucks in ETS2 and ATS for a more realistic driving feel.',
    author: 'Physics Team',
    game: 'ETS2',
    category: 'Physics',
    tags: ['physics', 'weight', 'inertia', 'realism'],
    version: '3.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a2a/ffffff?text=Truck+Physics',
    screenshots: ['https://placehold.co/800x450/2a3a2a/ffffff?text=Physics+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 92000,
    rating: 4.4,
    reviewCount: 4500,
    fileSize: '30 MB',
    dependencies: [],
    changelog: ['Updated weight values for all trucks'],
    features: ['Weight distribution system', 'Center of mass physics', 'Inertia modeling', 'Cargo weight effects'],
    requiredDLC: [],
    ratingBreakdown: { 5: 3600, 4: 675, 3: 180, 2: 36, 1: 9 },
    views: 320000,
    purchasesCount: 0,
  },
  {
    title: 'UTB Trailers',
    slug: 'utb-trailers',
    shortDescription: 'Universal trailer pack with various cargo types.',
    description: 'UTB Trailers adds a wide variety of trailers to ETS2 and ATS including flatbeds, reefers, tankers, and specialized cargo trailers.',
    author: 'Trailer Team',
    game: 'ETS2',
    category: 'Trailer',
    tags: ['trailer', 'cargo', 'variety', 'pack'],
    version: '6.0',
    supportedGameVersions: ['1.53', '1.52', '1.51'],
    thumbnail: 'https://placehold.co/400x225/2a4a3a/ffffff?text=UTB+Trailers',
    screenshots: ['https://placehold.co/800x450/2a4a3a/ffffff?text=UTB+1', 'https://placehold.co/800x450/2a4a3a/ffffff?text=UTB+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 165000,
    rating: 4.5,
    reviewCount: 8100,
    fileSize: '200 MB',
    dependencies: [],
    changelog: ['Added new reefer models', 'Updated cargo capacities'],
    features: ['Flatbed trailers', 'Reefer containers', 'Tanker trailers', 'Specialized cargo models'],
    requiredDLC: [],
    ratingBreakdown: { 5: 6480, 4: 1215, 3: 324, 2: 65, 1: 16 },
    views: 580000,
    purchasesCount: 0,
  },
  {
    title: 'Steering Wheel Mod',
    slug: 'steering-wheel-mod',
    shortDescription: 'Custom steering wheel options for all trucks.',
    description: 'Adds dozens of custom steering wheel designs to ETS2 including sport wheels, wooden wheels, leather wrapped, and LED display wheels.',
    author: 'Interior Custom',
    game: 'ETS2',
    category: 'Interior',
    tags: ['steering', 'wheel', 'interior', 'customization'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a2a2a/ffffff?text=Steering+Wheel',
    screenshots: ['https://placehold.co/800x450/2a2a2a/ffffff?text=Steering+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 72000,
    rating: 4.3,
    reviewCount: 3400,
    fileSize: '60 MB',
    dependencies: ['SiSL Mega Pack'],
    changelog: ['Added 20 new steering wheel designs'],
    features: ['Custom steering wheels', 'Sport and classic styles', 'LED display wheels', 'Leather and wood finishes'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2720, 4: 510, 3: 136, 2: 27, 1: 7 },
    views: 250000,
    purchasesCount: 0,
  },
  {
    title: 'Next-Gen Graphics Overhaul',
    slug: 'next-gen-graphics-overhaul',
    shortDescription: 'Complete visual overhaul with next-gen graphics quality.',
    description: 'Next-Gen Graphics Overhaul pushes ETS2 visuals to the limit with 8K textures, advanced shaders, realistic lighting, and optimized performance.',
    author: 'Visual Arts',
    game: 'ETS2',
    category: 'Graphics',
    tags: ['graphics', 'next-gen', 'textures', 'lighting', 'shaders'],
    version: '1.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a2a3a/ffffff?text=Next-Gen+GFX',
    screenshots: ['https://placehold.co/800x450/1a2a3a/ffffff?text=GFX+1', 'https://placehold.co/800x450/1a2a3a/ffffff?text=GFX+2', 'https://placehold.co/800x450/1a2a3a/ffffff?text=GFX+3'],
    price: 7.99,
    isFree: false,
    featured: false,
    status: 'Published',
    downloadCount: 48000,
    rating: 4.7,
    reviewCount: 2300,
    fileSize: '1.8 GB',
    dependencies: [],
    changelog: ['Initial release'],
    features: ['8K texture pack', 'Advanced PBR shaders', 'Realistic lighting system', 'Optimized for performance'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1840, 4: 345, 3: 92, 2: 18, 1: 5 },
    views: 170000,
    purchasesCount: 12000,
  },
  {
    title: 'Heavy Cargo Pack',
    slug: 'heavy-cargo-pack',
    shortDescription: 'Extreme heavy-haul cargo for specialized transport.',
    description: 'Adds massive heavy cargo loads including construction equipment, industrial machinery, and oversized loads requiring special permits and escort vehicles.',
    author: 'Cargo Masters',
    game: 'ETS2',
    category: 'Utility',
    tags: ['cargo', 'heavy', 'haul', 'oversized', 'special'],
    version: '2.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a4a/ffffff?text=Heavy+Cargo',
    screenshots: ['https://placehold.co/800x450/2a3a4a/ffffff?text=Cargo+1', 'https://placehold.co/800x450/2a3a4a/ffffff?text=Cargo+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 95000,
    rating: 4.4,
    reviewCount: 4600,
    fileSize: '150 MB',
    dependencies: [],
    changelog: ['Added new cargo models', 'Fixed trailer physics'],
    features: ['Oversized cargo loads', 'Special transport missions', 'Escort vehicle support', 'Heavy haul trailers'],
    requiredDLC: ['Heavy Cargo Pack DLC'],
    ratingBreakdown: { 5: 3680, 4: 690, 3: 184, 2: 37, 1: 9 },
    views: 330000,
    purchasesCount: 0,
  },
  {
    title: 'American Night Map',
    slug: 'american-night-map',
    shortDescription: 'Night driving experience map for ATS.',
    description: 'Experience American highways at night with this atmospheric map mod featuring neon-lit cities, dark rural roads, and stunning night skyboxes.',
    author: 'Night Riders',
    game: 'ATS',
    category: 'Maps',
    tags: ['map', 'night', 'usa', 'atmosphere', 'lighting'],
    version: '1.5',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/1a1a3a/ffffff?text=Night+Map',
    screenshots: ['https://placehold.co/800x450/1a1a3a/ffffff?text=Night+1', 'https://placehold.co/800x450/1a1a3a/ffffff?text=Night+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 32000,
    rating: 4.2,
    reviewCount: 1500,
    fileSize: '250 MB',
    dependencies: [],
    changelog: ['New night skyboxes', 'Added city lighting'],
    features: ['Night driving focus', 'Neon cityscapes', 'Rural darkness', 'Custom skyboxes'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1200, 4: 225, 3: 60, 2: 12, 1: 3 },
    views: 110000,
    purchasesCount: 0,
  },
  {
    title: 'Rigid Truck Addon',
    slug: 'rigid-truck-addon',
    shortDescription: 'Adds rigid truck and drawbar trailer combinations.',
    description: 'This mod adds rigid (straight) trucks with drawbar trailers to ETS2 featuring various body types including box, curtain, refrigerated, and tipper.',
    author: 'Rigid Mods',
    game: 'ETS2',
    category: 'Truck',
    tags: ['rigid', 'truck', 'drawbar', 'trailer', 'uk'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a2a/ffffff?text=Rigid+Truck',
    screenshots: ['https://placehold.co/800x450/2a3a2a/ffffff?text=Rigid+1', 'https://placehold.co/800x450/2a3a2a/ffffff?text=Rigid+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 56000,
    rating: 4.3,
    reviewCount: 2700,
    fileSize: '140 MB',
    dependencies: [],
    changelog: ['Added new body types', 'Fixed coupling physics'],
    features: ['Rigid truck chassis', 'Drawbar trailer system', 'Multiple body types', 'UK-spec configurations'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2160, 4: 405, 3: 108, 2: 22, 1: 5 },
    views: 200000,
    purchasesCount: 0,
  },
  {
    title: 'Realistic AI Traffic Sound',
    slug: 'realistic-ai-traffic-sound',
    shortDescription: 'Realistic traffic sounds from surrounding vehicles.',
    description: 'Adds realistic engine, tire, and horn sounds to AI traffic vehicles for a more immersive driving experience.',
    author: 'Audio Design',
    game: 'ETS2',
    category: 'Sound',
    tags: ['sound', 'traffic', 'ai', 'audio', 'immersion'],
    version: '1.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a3a3a/ffffff?text=AI+Sound',
    screenshots: ['https://placehold.co/800x450/2a3a3a/ffffff?text=AI+Sound+1'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 44000,
    rating: 4.1,
    reviewCount: 2100,
    fileSize: '65 MB',
    dependencies: [],
    changelog: ['Initial release'],
    features: ['AI vehicle engine sounds', 'Traffic horn variety', 'Tire noise simulation', 'Distance-based audio'],
    requiredDLC: [],
    ratingBreakdown: { 5: 1680, 4: 315, 3: 84, 2: 17, 1: 4 },
    views: 160000,
    purchasesCount: 0,
  },
  {
    title: 'Improved Weather System',
    slug: 'improved-weather-system',
    shortDescription: 'Dynamic weather with smooth transitions and variety.',
    description: 'Enhances the default weather system with smooth transitions between weather types, more variety, and realistic cloud formations.',
    author: 'Weather Studio',
    game: 'ETS2',
    category: 'Weather',
    tags: ['weather', 'dynamic', 'clouds', 'atmosphere'],
    version: '2.0',
    supportedGameVersions: ['1.53', '1.52'],
    thumbnail: 'https://placehold.co/400x225/2a4a4a/ffffff?text=Weather+System',
    screenshots: ['https://placehold.co/800x450/2a4a4a/ffffff?text=Weather+1', 'https://placehold.co/800x450/2a4a4a/ffffff?text=Weather+2'],
    price: 0,
    isFree: true,
    featured: false,
    status: 'Published',
    downloadCount: 68000,
    rating: 4.4,
    reviewCount: 3200,
    fileSize: '70 MB',
    dependencies: [],
    changelog: ['Smooth weather transitions', 'New cloud types'],
    features: ['Dynamic weather transitions', 'Realistic cloud formations', 'Improved precipitation', 'Atmospheric variety'],
    requiredDLC: [],
    ratingBreakdown: { 5: 2560, 4: 480, 3: 128, 2: 26, 1: 6 },
    views: 240000,
    purchasesCount: 0,
  },
]

async function seed() {
  try {
    await mongoose.connect(config.mongodbUri)
    console.log('Connected to MongoDB')

    await Mod.deleteMany({})
    console.log('Cleared existing mods')

    await Mod.insertMany(mods)
    console.log(`Seeded ${mods.length} mods`)

    await mongoose.disconnect()
    console.log('Done')
    process.exit(0)
  } catch (err) {
    console.error('Seed failed:', err)
    process.exit(1)
  }
}

seed()
